receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      exporters: [debug]
    logs:
      receivers: [otlp]
      exporters: [debug]